name: docker-size

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
      - name: ğŸ³ Calculate docker image size in ${{ github.base_ref }}
        id: docker_branch
        run:  |
          docker build . -t service
          image_size=$(docker images service | awk 'NR==2 {print $NF}')
          echo "base_image_size=$image_size" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: ğŸ³ Calculate docker image size in ${{ github.head_ref }}
        id: docker_base
        run:  |
          docker build . -t service
          image_size=$(docker images service | awk 'NR==2 {print $NF}')
          echo "head_image_size=$image_size" >> $GITHUB_OUTPUT
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: <docker-image-size>
          message: |
            ğŸ³ Size of the Docker Image the Base (${{ github.ref_name }}): **${{ steps.docker_branch.outputs.base_image_size }}**
            ğŸ³ Size of the Docker Image in this branch (${{ github.head_ref }}): **${{ steps.docker_branch.outputs.head_image_size }}**
