---
name: 'Todo to issue'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4"
        with:
          ISSUE_TEMPLATE: |
            #  âœ… Codebase TODO  âœ…

            ** ğŸ“ Title**: {{ title }}

            ** ğŸ”— URL**:
            {{ url }}

            <details><summary>**ğŸ“ Source of this issue**</summary>

            {{ snippet }}

            </details>
          AUTO_ASSIGN: true
          IGNORE: "./github/workflows/todo-to-issue-yml"
